apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    db: gamecloud-postgres
data:
  init.sql: |
    CREATE DATABASE gamecloud_catalog;
    CREATE DATABASE gamecloud_order;

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: gamecloud-postgres
  labels:
    db: gamecloud-postgres
spec:
  selector:
    matchLabels:
      db: gamecloud-postgres
  template:
    metadata:
      labels:
        db: gamecloud-postgres
    spec:
      containers:
        - name: gamecloud-postgres
          image: postgres:15.3
          env:
            - name: POSTGRES_USER
              value: user
            - name: POSTGRES_PASSWORD
              value: password 
          resources:
            requests:
              cpu: 100m
              memory: 60Mi
            limits:
              cpu: 200m
              memory: 120Mi
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d
              name: postgres-config-volume
      volumes:
        - name: postgres-config-volume
          configMap:
            name: postgres-config

---

apiVersion: v1
kind: Service
metadata:
  name: gamecloud-postgres
  labels:
    db: gamecloud-postgres
spec:
  type: ClusterIP
  selector:
    db: gamecloud-postgres
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
