include('../../../../config-service/Tiltfile')
include('../../../../api-gateway/Tiltfile')
include('../../../../logistic-service/Tiltfile')
include('../../../../order-service/Tiltfile')
include('../../../../catalog-service/Tiltfile')

update_settings(max_parallel_updates=1)
