version: "3.9"
services:
 
  catalog-service:
    depends_on:
      - gamecloud-postgres
      - config-service
    image: "ghcr.io/b3nk4n/gamecloud-catalog-service"
    container_name: catalog-service
    ports:
      - 9001:9001
      - 9999:9999
    environment:
      - BPL_JVM_THREAD_COUNT=64
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=9999
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - SPRING_DATASOURCE_URL=jdbc:postgresql://gamecloud-postgres:5432/gamecloud_catalog
      - SPRING_PROFILES_ACTIVE=demo

  order-service:
    depends_on:
      - gamecloud-postgres
      - config-service
      - catalog-service
    image: "ghcr.io/b3nk4n/gamecloud-order-service"
    container_name: order-service
    ports:
      - 9002:9002
      - 9998:9998
    environment:
      - BPL_JVM_THREAD_COUNT=64
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=9998
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - SPRING_R2DBC_URL=r2dbc:postgresql://gamecloud-postgres:5432/gamecloud_order
      - SPRING_FLYWAY_URL=jdbc:postgresql://gamecloud-postgres:5432/gamecloud_catalog
      - CLIENT_CATALOG_SERVICE_URI=http://catalog-service:9001

  logistic-service:
    depends_on:
      - gamecloud-rabbitmq
      - config-service
    image: "ghcr.io/b3nk4n/gamecloud-logistic-service"
    container_name: logistic-service
    ports:
      - 9003:9003
      - 8003:8003
    environment:
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8003
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - SPRING_RABBITMQ_HOST=gamecloud-rabbitmq

  api-gateway:
    depends_on:
      - gamecloud-keycloak
      - gamecloud-redis
      - config-service
    image: "ghcr.io/b3nk4n/gamecloud-api-gateway"
    container_name: api-gateway
    ports:
      - 9000:9000
      - 8000:8000
    environment:
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8000
      - CATALOG_SERVICE_URL=http://catalog-service:9001
      - ORDER_SERVICE_URL=http://order-service:9002
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - SPRING_REDIS_HOST=gamecloud-redis
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI=http://host.docker.internal:8080/realms/GameCloud

  config-service:
    image: "ghcr.io/b3nk4n/gamecloud-catalog-service"
    container_name: config-service
    ports:
      - 8888:8888
      - 8999:9999
    environment:
      - BPL_JVM_THREAD_COUNT=64
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8999
 
  gamecloud-postgres:
    image: "postgres:15.3"
    container_name: gamecloud-postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  gamecloud-redis:
    image: "redis:7.0.12"
    container_name: gamecloud-redis
    ports:
      - 6379:6379

  gamecloud-rabbitmq:
    image: rabbitmq:3.12-management
    container_name: gamecloud-rabbitmq
    ports:
      - 5672:5672
      - 15672:15672 # management UI
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf

  gamecloud-keycloak:
    image: keycloak/keycloak:22.0.1
    container_name: gamecloud-keycloak
    command: start-dev --import-realm
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    environment:
      - KEYCLOAK_ADMIN=user
      - KEYCLOAK_ADMIN_PASSWORD=password
    ports:
      - 8080:8080
